---

services:
  clickhouse-logs-streamer:
    # build:
    #   context: "."
    #   dockerfile: "Dockerfile"
    image: "ghcr.io/iqover8000/clickhouse-system-log-streamer:0.1.0"
    container_name: "clickhouse-logs-streamer"
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    environment:
      CH_HOST: "${CH_HOST}"
      CH_PORT: "${CH_PORT:-8443}"
      CH_USER: "${CH_USER:-default}"
      CH_PASSWORD: "${CH_PASSWORD}"
      CH_DATABASE: "${CH_DATABASE:-default}"
      CH_SECURE: "${CH_SECURE:-true}"
      CH_VERIFY: "${CH_VERIFY:-true}"

      CH_LOG_TABLE: "${CH_LOG_TABLE:-system.text_log}"
      CH_LOG_TIMESTAMP_COLUMN: "${CH_LOG_TIMESTAMP_COLUMN:-event_time_microseconds}"
      CH_LOG_SEVERITY_COLUMN: "${CH_LOG_SEVERITY_COLUMN:-level}"
      CH_LOG_MESSAGE_COLUMN: "${CH_LOG_MESSAGE_COLUMN:-message}"

      LOG_SEVERITY: "${LOG_SEVERITY:-error}"
      LOG_OUTPUT_FORMAT: "${LOG_OUTPUT_FORMAT:-raw}"

      CH_OFFSET_TABLE: "${CH_OFFSET_TABLE:-default.logs_streamer_offsets}"
      STREAMER_ID: "${STREAMER_ID:-default-streamer}"
      POLL_INTERVAL_SECONDS: "${POLL_INTERVAL_SECONDS:-10}"
      BATCH_SIZE: "${BATCH_SIZE:-1000}"
      HEALTH_STALE_SECONDS: "${HEALTH_STALE_SECONDS:-30}"
      LOOKBACK_MAX_SECONDS: "${LOOKBACK_MAX_SECONDS:-3600}"

      FLASK_HOST: "${FLASK_HOST:-0.0.0.0}"
      FLASK_PORT: "${FLASK_PORT:-8080}"
